<?php

namespace WebsiteBundle\Repository;

/**
 * HeadTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeadTopicRepository extends \Doctrine\ORM\EntityRepository
{
}
