website_index:
    path:    /
    defaults: { _controller: WebsiteBundle:Index:index }

website_signup:
    path:    /signup
    defaults: { _controller: WebsiteBundle:Signup:signup }

website_forum:
    path:    /forum
    defaults: { _controller: WebsiteBundle:Forum:forum }

website_topic:
    path:    /forum/{id}
    defaults: { _controller: WebsiteBundle:Topic:topic }

website_topic_add:
    path:    /forum/{id}/add/sujet
    defaults: { _controller: WebsiteBundle:Addsujet:addsujet }

website_reply_add:
    path:    /forum/sujet/{id}/add/reply
    defaults: { _controller: WebsiteBundle:Addreply:addreply }

website_view_topic:
    path:    /forum/sujet/{id}
    defaults: { _controller: WebsiteBundle:Viewsujet:viewsujet }

website_edit_topic:
    path:    /forum/sujet/{id}/edit
    defaults: { _controller: WebsiteBundle:Addsujet:editsujet }