website_index:
    path:    /
    defaults: { _controller: WebsiteBundle:Index:index }

website_signup:
    path:    /signup
    defaults: { _controller: WebsiteBundle:Signup:signup }

website_forum:
    path:    /forum
    defaults: { _controller: WebsiteBundle:Forum:forum }

website_topic:
    path:    /forum/{id}
    defaults: { _controller: WebsiteBundle:Topic:topic }