website_index:
    path:    /
    defaults: { _controller: WebsiteBundle:Index:index }

website_signup:
    path:    /signup
    defaults: { _controller: WebsiteBundle:Signup:signup }

website_forum:
    path:    /forum
    defaults: { _controller: WebsiteBundle:Forum:forum }

website_topic:
    path:    /forum/{id}
    defaults: { _controller: WebsiteBundle:Topic:topic }

website_topic_add:
    path:    /forum/add/sujet
    defaults: { _controller: WebsiteBundle:Addsujet:addsujet }